# @Author: Will Scott <willscottuk>
# @Date:   14/06/2017 21:12
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 21/01/2018 19:15

# This package deals with the internal climate.

homeassistant:
  customize:
    sensor.heating_temperature:
      friendly_name: 'Current Temperature'
    sensor.heating_humidity:
      friendly_name: 'Indoor Humidity'
    sensor.heating_set_temp:
      friendly_name: 'Target Temperature'
      icon: mdi:nest-thermostat
    sensor.heating_heating:
      friendly_name: 'Heating Power'
      icon: mdi:fire
    sensor.heating_link:
      friendly_name: 'Tado Status'
      icon: mdi:nest-thermostat
    sensor.heating_tado_mode:
      friendly_name: 'Tado Mode'
      icon: mdi:nest-thermostat
    climate.heating:
      custom_ui: none

tado:
  username: !secret tado_user
  password: !secret tado_pass

sensor:
  - platform: template
    sensors:
      heating_set_temp:
        value_template: '{{ states.sensor.heating_temperature.attributes.setting }}'
        friendly_name: 'Target Temperature'
        unit_of_measurement: 'ºC'

group:
  Internal Details:
    - sensor.heating_temperature
    - sensor.heating_humidity
    - sensor.basecamp_living_room_air_quality
    - sensor.heating_set_temp
    - sensor.heating_heating
    - sensor.heating_link
    - sensor.heating_tado_mode
  Internal:
    - sensor.heating
    - sensor.air_quality
    - sensor.electricity_usage

automation:
  - alias: 'Start-up update'
    trigger:
      platform: homeassistant
      event: start
    action:
      service: python_script.climate_status

  # Time interval update (each 1 minute)
  - alias: 'Time interval updates'
    hide_entity: True
    initial_state: 'on'
    trigger:
      - platform: time
        minutes: '/1'
        seconds: 00
    action:
      - service: python_script.climate_status
        data_template:
          event: "{{ trigger.event }}"
