# @Author: Will Scott <willscottuk>
# @Date:   14/06/2017 21:02
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 09/12/2017 13:33

# This package deals with internal monitoring - both inside the flat and inside the server

homeassistant:
  customize:
    sensor.power_usage:
      friendly_name: 'Electricity'
      icon: mdi:speedometer
    sensor.speedtest_ping:
       icon: mdi:pulse
    sensor.speedtest_download:
       icon: mdi:cloud-download
    sensor.speedtest_upload:
       icon: mdi:cloud-upload
    sensor.disk_use_mediabasecampsherpa:
       friendly_name: "Sherpa"
    sensor.disk_use_mediabasecampdragonfly:
       friendly_name: "Dragonfly"
    sensor.since_last_boot:
       friendly_name: "Uptime"

switch:
  - platform: tplink
    host: !secret dryer_ip
    name: "Tumble Dryer"

sensor:
  -  platform: loopenergy
     electricity:
       electricity_serial: !secret loop_serial
       electricity_secret: !secret loop_secret
  - platform: speedtest
    minute:
      - 45
    monitored_conditions:
      - download
      - upload
    server_id: 4078
  - platform: fastdotcom
    minute:
      - 15
  - platform: statistics
    entity_id: sensor.power_usage
    name: Power Stats
    sampling_size: 25
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: !secret disk
      - type: disk_use_percent
        arg: !secret disk2
      - type: memory_use_percent
      - type: processor_use
  - platform: template
    sensors:
      electricity_usage:
        friendly_name: "Electricity Usage"
        value_template: >-
          {%- if states("sensor.power_stats_mean") | float < 0.2 -%}
            low
          {%- elif states("sensor.power_stats_mean") | float < 1.0 -%}
            moderate
          {%- elif states("sensor.power_stats_mean") | float >= 1.0 -%}
            high
          {%- else -%}
            unknown
          {%- endif -%}
      tumble_dryer_current:
        friendly_name: 'Tumble Dryer Current'
        value_template: '{{ states.switch.tumble_dryer.attributes["current_consumption"].split(" ")[0] }}'
        unit_of_measurement: 'W'

  - platform: travisci
    api_key: !secret travisci

group:
  System:
    - sensor.cpu_use
    - sensor.disk_use_mediabasecampsherpa
    - sensor.disk_use_mediabasecampdragonfly
  Speed:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.fastcom_download
  Power:
    -  sensor.power_usage
    -  sensor.power_stats_mean
    -  sensor.electricity_usage
    -  sensor.tumble_dryer_current

automation:
  - alias: "Configuration Update"
    trigger:
      platform: state
      entity_id: sensor.ambassadrhomeassistant_last_build_finished_at
    condition:
      - condition: state
        entity_id: sensor.ambassadrhomeassistant_last_build_state
        state: 'passed'
      - condition: template
        value_template: '{{states.sensor.ambassadrhomeassistant_last_build_finished_at.attributes["Commit Branch"] == "master"}}'
      - condition: template
        value_template: '{{states.sensor.ambassadrhomeassistant_last_build_finished_at != "unknown"}}'
    action:
      - service: script.configuation_update

script:
  configuation_update:
    sequence:
      - service: shell_command.git_pull
      - service: notify.will
        data_template:
          title: "\U000026A1 Restarting HomeAssistant Now"
          message: "Restarting in 30 seconds to update to new build"
      - delay: 00:00:30
      - service: shell_command.restart_homeassistant

shell_command:
  restart_homeassistant: 'sudo service home-assistant@basecamp restart'
  git_pull: 'bash /home/basecamp/.homeassistant/scripts/git_pull.sh'
